# Generated by Django 4.0.1 on 2022-02-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_acceleration_features_acceleration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='student',
        ),
    ]
